name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          playlist_id: PLZPZq0r_RZON03iKBjYOsOKr1-TD7z2lH
            description: "The playlist ID to use for the feed"
            required: true
            default: ""
          lang:
            description: "The language you want your cards description to use"
            required: false
            default: "en"
          comment_tag_name:
            description: "The name of the comment tag to use for the cards"
            required: false
            default: "YOUTUBE-CARDS"
          max_videos:
            description: "The maximum number of videos to display"
            required: false
            default: "6"
